import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { ClerkProvider } from "@/components/clerk-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider>
          <div className="flex flex-col min-h-dvh justify-stretch">
            <Header />
            <div className="flex grow items-stretch">
              <div className="border-r border-gray-500 w-72">
                <p>Sidebar here</p>
              </div>
              <main className="w-full">{children}</main>
            </div>
          </div>
        </ClerkProvider>
      </body>
    </html>
  );
}
